dj-database-url = "^1.2.0"
psycopg2-binary = "^2.9.5"
whitenoise = {extras = ["brotli"], version = "^6.2.0"}
gunicorn = "^20.0.4"


[tool.poetry]
name = "deploy_renderer"
version = "0.1.0"
description = ""
authors = ["email"]