# Generated by Django 3.2 on 2022-12-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name_plural': 'Project Type'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skill'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='my_service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='hobby',
            new_name='skill',
        ),
    ]
