# Generated by Django 3.2 on 2022-12-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20221222_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
