# Generated by Django 5.2.3 on 2025-06-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0002_delete_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverheader",
            name="pdf",
            field=models.FileField(default="", upload_to="upload-images/"),
        ),
    ]
