# Generated by Django 3.2 on 2022-12-23 01:51

import Frontend.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='hobbies',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myservices',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=datetime.datetime(2022, 12, 23, 1, 50, 17, 269451, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='content',
            field=models.TextField(default=datetime.datetime(2022, 12, 23, 1, 50, 25, 413508, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='average',
            field=models.CharField(default=datetime.datetime(2022, 12, 23, 1, 50, 50, 180002, tzinfo=utc), max_length=3, validators=[Frontend.models.is_digit]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='month_flow',
            field=models.CharField(default=datetime.datetime(2022, 12, 23, 1, 51, 4, 285994, tzinfo=utc), max_length=3, validators=[Frontend.models.is_digit]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='week_flow',
            field=models.CharField(default=datetime.datetime(2022, 12, 23, 1, 51, 11, 488789, tzinfo=utc), max_length=3, validators=[Frontend.models.is_digit]),
            preserve_default=False,
        ),
    ]
